# dataset
dataset: DistillRecDial
tokenize:
  rec: gpt2
  conv: gpt2
# dataloader
utterance_truncate: 80
conversation_truncate: 40
scale: 1
# model
# rec
rec_model: ReDialRec
autorec_layer_sizes: [ 512, 256 ]
autorec_f: sigmoid
autorec_g: sigmoid
# conv
conv_model: ReDialConv
# embedding: word2vec
embedding_dim: 256
utterance_encoder_hidden_size: 256
dialog_encoder_hidden_size: 256
dialog_encoder_num_layers: 1
use_dropout: True
dropout: 0.3
decoder_hidden_size: 256
decoder_num_layers: 1
# optim
rec:
  epoch: 200
  batch_size: 1024
  optimizer:
    name: AdamW
    lr: !!float 5e-3
  early_stop: true
  impatience: 15
  stop_mode: min
conv:
  epoch: 50
  batch_size: 128
  optimizer:
    name: AdamW
    lr: !!float 1e-3
  early_stop: true
  impatience: 3
  stop_mode: min
